### ISSUE TITLE
Offline feed takeover

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#1]
When the user stops streaming the stream should be replaced with an "offline" visual state.  This can be a static image that's transcoded into the server's existing HLS stream(s) or a short video clip that gets added to.  Essentially just appending to the HLS playlists after the user drops their RTMP.

**Comment by gabek** [comment]
Server-side stitching of a non-live stream to show an offline state in the stream itself has been added and I'm testing it.

**Comment by gingervitis** [comment]
This is on my TODO list!

**Comment by gabek** [comment]
Oh sorry, I should be clearer, that this is actually creating an offline feed server-side.  That's different than whatever you want to do with the web UI.

**Comment by gabek** [comment]
The offline video segments are being generated, and the variant's playlists have the segments in them, but if you're watching an "online" feed, and then the "offline" segments get added, the player just gives up trying to play them.  It may have something to do with it coming from a brand new source and having a whole new header to them, as the player is expecting segments that continue the existing stream, not essentially starting a new one.

I'll keep looking into it.  With the new transcoder it should be easier to make changes to tweak this until it works.

**Comment by gabek** [comment]
This is working in the new transcoder.
