### ISSUE TITLE
A chat user will see their own handle highlighted

### ISSUE THREAD

**Issue by lindner** [gabek/owncast#100]
If someone mentions my handle in a message display it would be useful to display the chat message or the handle text in a highlighted color, so I can notice when people mention me in a fast moving chat.

**Comment by lindner** [comment]
and yes, I know this is basically spec'ing a basic IRC client /shruggie

**Comment by gabek** [comment]
IRC clients have done it right before!

This is a great suggestion, I like it.  Thanks!

**Comment by gabek** [comment]
The chat updates begin!
