### ISSUE TITLE
Show progress bar during live

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#11]
Videojs hides the progress bar during live content.  @gingervitis thinks it would be useful to show it and be able to seek back, so let's enable it.  There's probably a way to force Videojs to show it.

**Comment by graywolf336** [comment]
I like this, it's how YouTube live does it and then you can click the "live" and it'll jump forward to the current live video

**Comment by gabek** [comment]
I'm not sure if this is something we still care about since for most situations the max number of segments that are able to be seeked to in the past are very few.  Even if you pause and then unpause it seems Videojs brings you to live, not to the point where you paused.  But it seems like videojs has a whole page about the live UI that might have some answers to turning things on/off.  https://docs.videojs.com/tutorial-live.html#the-new-user-interface

**Comment by gabek** [comment]
More details about `liveUI` here: https://blog.videojs.com/video-js-7-4/.  I'm not sure why we're not seeing it.
