### ISSUE TITLE
Information + documentation site

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#116]
Not something we need now, but as documentation grows it might be nice to have a place to refer to that's not just in the Github repo.

We could probably just use Hugo and grab a theme from https://themes.gohugo.io/tags/documentation/ and copy our documentation into it.  Host it via Github pages.  I kind of liked [this theme](https://themes.gohugo.io/theme/ace-documentation/).

**Comment by jeyemwey** [comment]
I can certainly help with that. Maybe, we can add a landing page and a "features" page and all that stuff.

To keep things simple, I'd move this into a new repository.

**Comment by gabek** [comment]
Awesome!  I agree a new repo makes sense.  From a logistical standpoint, would it make sense to create a Github organization for owncast since we're looking to create another repository?  I figure it's best to do it now and only change references for one repo instead of creating a new one under my user and then changing references to two of them later.  But I don't know if that's overkill.  @gingervitis @graywolf336

**Comment by graywolf336** [comment]
Yeah, if we're going to be adding another repository underneath the "owncast" umbrella it probably does make sense to create an organization here on GitHub for it.

**Comment by gabek** [comment]
Alright, organization created!  I invited all of you and created the https://github.com/owncast/owncast.github.io repo for Github Pages.  I have a domain of `owncast.online` I registered previously, unless people really hate that URL I can CNAME it to the github page.  I haven't moved over the actual project repo.  I'm pretty sure Github will redirect, but I'm not sure if anything else will break, so I wanted to make sure everyone was cool with it and aware first.

@jeyemwey It's all yours if you want to run with it!  Thank you!

**Comment by gabek** [comment]
@jeyemwey You're awesome!  I pointed `owncast.online` to the site you setup and it's working great.  I moved some of the content around so things had their own files and removed the bulk of the content from the main page.  This new site is a far better way of digging through the documentation than Github.

**Comment by jeyemwey** [comment]
I only converted the existing content to a webpage :)

Please move the stuff as much as you like.

**Comment by gabek** [comment]
Done!  Things look to be redirecting fine, but let me know if you run into something that needs to be repointed or fixed.

**Comment by gabek** [comment]
One last update, I removed the `doc` directory in the `owncast/owncast` repo to remove confusion about where the most up to date documentation is.  I did, however, link it as a submodule so people can click through if they're on Github, or for convenience if you're in the repo and want to update the documentation.  Apologies to anybody who may have linked to documentation previously.
