### ISSUE TITLE
General performance (transcoding, segmenting, uploading, etc)

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#12]
This is a placeholder thread where I can document experiments and have conversations about performance.

**Comment by gabek** [comment]
@graywolf336 Good news!  I found the "passthrough" setting wasn't actually working.  So with the recent fix if you enable it you should see large performance gains.  Attached is a before and after example of CPU usage.

However, the side effect of passthrough is the final result can be much larger segments.  But on the other hand you could tweak the encoder on your client to send smaller video.  This isn't really the real solution for performance, since it's just disabling transcoding, but it's a start.

![image](https://user-images.githubusercontent.com/414923/85100390-e60c0b00-b1b4-11ea-90ed-1c56a7100c09.png)

**Comment by graywolf336** [comment]
Very nice! I will test it out in a little bit and see what happens on the $5 digital ocean droplet.

**Comment by graywolf336** [comment]
@gabek Just tested it, pretty good results so far. With OBS, it doesn't drop any frames. But with ProPresenter it does drop frames just not as much as it used to. So, it has improved 👏

**Comment by gabek** [comment]
With passthrough enabled, running a stream long enough will gradually continue to increase CPU us.  I'll have to see if this is a ffmpeg thing, or the application.

![image](https://user-images.githubusercontent.com/414923/85183380-5f9d0b00-b240-11ea-81ea-9bb4b0e6afa7.png)

**Comment by gabek** [comment]
Good news!  I found if external storage is disabled the CPU usage stays flat (at least for the duration I've been testing).  This means means any of these things are to blame:

* The filesystem polling (maybe)
* The playlist generator (maybe)
* The actual file uploads (probably not)

But these are some very specific points I can look at now to narrow the issue down.

![image](https://user-images.githubusercontent.com/414923/85187086-d55da280-b251-11ea-8004-55c061b5f0b2.png)

**Comment by gabek** [comment]
Attached is a profiling session.  It looks to mostly be i/o based, with the majority of the work being done with the RTMP handling.  But that doesn't make sense then why when I turn off external storage there's no longer an issue.  RTMP handling happens the same regardless.  Still digging.

[profile.pdf](https://github.com/gabek/owncast/files/4808597/profile.pdf)

**Comment by gabek** [comment]
Wins!

One small win by adding a lookup table for segments, but the big one being that ffmpeg wasn't actually limiting the number of items in the variant's playlist.  So each time the playlist was parsed and regenerated the `scanner` was taking longer and longer to go through it.  I would never guess it would become *that* slow, even with hundreds of lines, but I guess it's just not built for that.

Fixing ffmpeg's segment limit in the playlist made it many times faster, and as a side effect it fixed the auto-deletion of old segments on the local disk as well, since because they weren't being dereferenced in the variant's playlist before they weren't being deleted.

After streaming an hour: 

```
$ grep .ts hls/0/stream.m3u8 |wc -l ; ls hls/0/*.ts |wc -l
50
62
```

Still room for improvement across the board, but I hope this marks a noticeable improvement.

**Comment by gabek** [comment]
For future reference it was `hls_playlist_type` overriding the playlist size settings:

https://github.com/gabek/owncast/commit/22a1eb90ab84d90027d166b376c114bf03431497

**Comment by gabek** [comment]
Turning transcoding back on, as expected, still creates a huge spike in the CPU, but at least there's not the additional overhead of non-transcoding work making it worse.

**Comment by gabek** [comment]
I wanted to do some multi-bitrate testing so I grabbed a $10/mo machine from linode.

With the new transcoder (https://github.com/gabek/owncast/pull/27) I'm able to have one passthrough and one transcoded variant and it seems to be acceptable on this machine.  It's still only a single CPU, though, so it's not like it can parallelize the work against a bunch of cores.

![image](https://user-images.githubusercontent.com/414923/85519055-c3fbf980-b5b5-11ea-9d63-539152f0a601.png)

**Comment by gabek** [comment]
@graywolf336 You mentioned upload speeds dropping shortly after starting streaming.  I just looked at my inbound speeds from the session I did last night on my $5 Linode machine and it looks to be relatively stable throughout.  But this is just a single datapoint. I'm not sure what the spikes are.

![image](https://user-images.githubusercontent.com/414923/85959981-b7c8c100-b954-11ea-89c6-2fb9f4d66211.png)

**Comment by graywolf336** [comment]
Okay, I'll look into my issues. I have a feeling it is ISP related since I was able to do it from my phone's tether and it was stable. But I went to another place and had the same issues with my laptop. I'll try to determine the true cause this week

**Comment by graywolf336** [comment]
<img width="984" alt="Screen Shot 2020-07-12 at 11 25 45 AM" src="https://user-images.githubusercontent.com/850391/87251614-7c3cf500-c432-11ea-928e-7c228a687c4d.png">
Here a cpu graph from a $15 Digital Ocean instance. Transcoding two different qualities

**Comment by gabek** [comment]
Closing this as it seems like we've reached some performance stability.  Specific future topics can have their own issues opened.
