### ISSUE TITLE
Project Restructure

### ISSUE THREAD

**Issue by graywolf336** [gabek/owncast#16]
What would be your thoughts on the following project structure:

```bash
├── config 
│   └── config.go
├── controllers (http controllers)
│   ├── chat.go
│   └── static.go
├── core (the logic lives here)
│   ├── ffmpeg/
│   │   ├── offline.go
│   │   └── start.go
│   ├── rtmp/
│   │   ├── handler.go
│   │   └── server.go
│   ├── storage/ (implementations)
│   │   ├── ipfs.go
│   │   └── aws.go
│   ├── storage.go (interface)
│   ├── core.go
│   ├── stats.go
├── models (definitions for how data will be handled)
│   ├── stat.go
│   ├── server.go
│   └── etc.go
├── utils
│   └── utils.go
├── static (stays the same)
│   └── logo.png (etc)
├── webroot (stays the same)
│   ├── img/
│   ├── js/
│   ├── static/
│   ├── styles/
│   ├── vendor/
│   └── index.html
├── go.mod
├── go.sum
├── main.go
├── config.sample.yaml
├── README.md
├── Dockerfile
└── .gitignore
```

This is a massive difference from the current structure of the project and I am willing to start the PR to move it and work on the restructuring. Curious to hear your thoughts

**Comment by gabek** [comment]
Music to my ears!  I think this is great!  Currently it's been in the typical "this is a new project and I don't know what we need, so no use prematurely trying to organize it", but I think it's past that now and it makes sense to add structure to it.  I think the layout you proposed makes as much sense as any.  I really appreciate the thought you put into it.  Go for it!

**Comment by graywolf336** [comment]
Awesome!! I'll get to work on it and maybe have something by Monday, unless I get enough time to work on it this evening :)
