### ISSUE TITLE
On new RTMP stream, wipe out all the references/files related to the previous stream.

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#19]
Either on RTMP disconnect or RTMP re-connect we should wipe all the segment references and on-disk files related to the previous session, since they no longer matter.  We wipe the files on launch if the user were to re-launch the service, but if it stays up that currently doesn't take place.

**Comment by graywolf336** [comment]
Wonder if there needs to be a grace period built in to where it picks back up where it left off if under the grace period threshold? 🤔

**Comment by gabek** [comment]
That's a good idea.  I'm already doing the same thing for determining  the "max viewer" count for a "session", since if a user stops streaming and re-starts shortly after, it makes sense to call it the same "session".  So doing the same when cleaning house makes sense, too.

**Comment by graywolf336** [comment]
Wonder if we should make that threshold configurable or leave it hard coded?

One of the issues we face at Rocket.Chat is that it is **too** configurable and people find it hard to use because of so many settings and ways to customize it...which is an odd situation but does make sense and is a thing, or so searching the web for `choice paralysis` returns for several results and so so `choice paralysis ux`

**Comment by gabek** [comment]
I could totally see that.  I think for a lot of things starting by hardcoding and then changing it to be configurable if the need arises might make sense.  If somebody is already trying to decide what bitrates and stuff they want to provide then asking them things like "how long is a session?" is probably just adding more things for somebody to worry about without a lot of benefit.  I think similar things customizing things like how many retries in uploading to external storage.  There might be a circumstance where somebody has a really lousy network and might need to crank that value up, but is probably not something people need to think about on initial setup.  In fact, it might make sense to simplify even what we have.  I'm not sure if users need to select their max HLS playlist length or segment size or not.  Segment size might be useful.

**Comment by gabek** [comment]
Right now we immediately change the stream to the "offline" stream when RTMP drops so anybody tuning in will see that it's offline.  In that case the stream is actually changed to completely different content.

With the idea of a grace period we wouldn't be able to go to an "offline" state for N minutes until after a disconnect in order to keep the HLS playlist intact in case the streamer immediately comes right back, and we can continue appending to the stream.

A lot of this is riding on the fact that we want to allow users to seek backwards in a live stream.  While this is nice functionality, I'm beginning to think it's more problems than it's worth as we have to guarantee the past still exists in both the HLS playlist and the backing segments on disk.

**Comment by gabek** [comment]
We're already cleaning up files at different times, so I think the original idea here is overkill, at least for now.  Closing.
