### ISSUE TITLE
Misc chat updates

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#26]
While in the future I'm sure there will be a major update, I wanted to add an issue for short term things to add.

* [x] Change message IDs from being client generated to server generated.  Mentioned again here: https://github.com/gabek/owncast/pull/25#discussion_r444411525
* [x] Persist the chat. Mentioned here https://github.com/gabek/owncast/pull/18#discussion_r443892798
* [x] @gingervitis suggested disabling chat when a stream is no longer active.  A timeout here would make sense, to allow chat after N minutes of a stream being disconnected, but lock it down when we think a "session" has ended.
* [x] Include timestamps with each message

**Comment by graywolf336** [comment]
Updated the list and added persist chat

**Comment by gabek** [comment]
**Disable chat after stream ends.**

With https://github.com/gabek/owncast/commit/8878ca1e88fe6f79f27ef0369334fc8e6e27b1b6 the web frontend now knows the time the stream disconnected.  We can add a grace period so N minutes after a disconnect is when the chat is locked down.  What should that value be?  5 minutes comes to mind as a middle ground.  Anything longer than that and the streamer probably isn't coming back, but I could see somebody dropping off for a few minutes for whatever reason.  Rebooting their computer, changing streaming settings, etc.  What do you think?

**Comment by gabek** [comment]
**Persist chat**

How far back should we persist?

We were earlier talking about Boltdb, but it might make more sense to use SQLite so we can efficiently query against timestamps and use it more as live storage than just on-disk source of restoring an array of messages.

**Comment by gingervitis** [comment]
I'll look into implementing checkbox 3 - with tis logic
When `status.online` has flipped to `false`; then disable chat after X time.

**Comment by gingervitis** [comment]
Re: persisting chat - include timestamps with each message.

**Comment by gabek** [comment]
@graywolf336 Curious about your thoughts on using an ORM like https://github.com/go-gorm/gorm for working with the chat persistence, have you ever used it or anything similar?  I've only used the `database/sql` stuff, but I'm curious if there's any niceties around an ORM or if it's worth it for something simple like this.

**Comment by gabek** [comment]
Added basic chat persistence.
