### ISSUE TITLE
Consolidate frontend & backend configs

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#30]
I think it would be nice to have a single place to make changes and not have to specify that you're talking about the backend config vs. the frontend config, especially in initial setup and in documentation.

Since we're already pulling in `config.json` on the frontend asynchronously we could simply create a `/config` endpoint that returns the same values `config.json` does based on the values in `config.yaml` and point there instead.

No rush to do this, since having a standalone frontend config right now allows faster iteration on the web UI, but would this be a positive change eventually?  What are your thoughts @gingervitis ?

**Comment by gingervitis** [comment]
After clarifying with @gabek how this would work, I think it currently makes sense to put this all the info into one file. I like the idea of having set restricted types of these fields which would allow us to have a more consistent and controllable look and feel across Owncast instances.

And in this case, if we ever need to add a new configurable frontend field, all instances would need to be updated to use it because the config structure has changed and the frontend markup will have most likely changed.

**Comment by gingervitis** [comment]
..On that note, can I make a request to add a couple fields to the config? 😁 


- allow for different logo image sizes, 
```
logo: {
  small: "logo64x64.png",
  large: "logo256x256.png",
},
...
```

- string to the "extra" static info `content.md` field.. Perhaps something along the lines of:
```
{
  ...
  extraUserInfoFileName: "/static/content-example.md",
}
```
(Sorry I can't think of a better name for that right now)

**Comment by gabek** [comment]
On it!

**Comment by gabek** [comment]
@graywolf336 Heads up, this is changed in master, so now both frontend and backend has a single config location.

**Comment by graywolf336** [comment]
Awesome!! 🎉

**Comment by gingervitis** [comment]
@gabek One more request, regarding the social list in the config-
Can you make that list an array, that would end up looking like this:
[
{platform: "facebook", url: "http.."},
{platform: "instagram", url: "http.."}
]

This will let users order their social acts by priority.

**Comment by gabek** [comment]
Ok, it now looks like this:

```
"socialHandles": [
{
"platform": "twitter",
"url": "http://twitter.com/owncast"
},
{
"platform": "instagram",
"url": "http://instagram.biz/owncast"
},
{
"platform": "facebook",
"url": "http://facebook.gov/owncast"
},
{
"platform": "tiktok",
"url": "http://tiktok.cn/owncast"
},
{
"platform": "soundcloud",
"url": "http://soundcloud.com/owncast"
}
```
