### ISSUE TITLE
Search results for an Owncast instance shows only template tags

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#36]
I'm guessing some HTML metadata tag should resolve this?

![image](https://user-images.githubusercontent.com/414923/86016852-2c910f00-b9d8-11ea-83a3-9e295a2a8810.png)

**Comment by gabek** [comment]
@gingervitis Want to put this on your radar in case you have an easy fix.

**Comment by graywolf336** [comment]
Is this because Vue is in development mode? (I've never used Vue before so this is a shot in the dark)

**Comment by gabek** [comment]
I think it's because it's client-rendered, so unless the search engine runs the Javascript and scrapes the output, I guess all it has is the raw templates.  I've run into the same thing with React.

**Comment by gingervitis** [comment]
Hmm, you'll need to do some server side rendering. If we're reading a config with JS on the client side for the entire thing, this is what we'll get. We could have a blurb somewhere about Owncast, the service itself hardcoded somewhere on the page. Let me know what copy you'd like to put it.

**Comment by gabek** [comment]
Actually now that the config file is shared spitting out a server-rendered page with just a blurb in it, so search engines/opengraph have metadata would be really straightforward.  I'll do that at some point.

**Comment by gabek** [comment]
Ok I threw something together.

**Comment by gingervitis** [comment]
FYI you'll also need to consider the document title, other this will happen.
<img width="185" alt="image" src="https://user-images.githubusercontent.com/9563255/86103895-30716f80-ba72-11ea-82a0-26ed12e375ac.png">

**Comment by gabek** [comment]
That should be ok with this, https://github.com/gabek/owncast/commit/ea9a1a3afda467a83848d387e85ee6acbfb9b5ec#diff-54d8f3681bfad6fcfe4117bbdf73697bR7, right?

**Comment by gingervitis** [comment]
Oh interesting, so how does it get replaced by index.html?

**Comment by gabek** [comment]
The main index.html will get swapped out with the server-rendered version if the backend detects that the client requesting it is a web crawler/bot here: https://github.com/gabek/owncast/commit/b4c9654dacda0318145af7f13deb096db182e399#diff-67de5c415112a3133605aca0859176cfR34

![image](https://user-images.githubusercontent.com/414923/86187960-0bbcdc80-baf2-11ea-9a01-85cc2e2533df.png)

**Comment by gabek** [comment]
Aside from the separate server-rendered page, currently the `title` tag is not a part of the Vue app, right?  Should we move `app-container` to be the id of the `html` tag instead?  Is that even allowed?  Or should we just `getElementsByTagName` the title tag and set it outside of Vue?

**Comment by gingervitis** [comment]
Actually I still need to set the <title> tag in javascript with the config data right after getting it. (document.title)

**Comment by gabek** [comment]
Oh that's way easier then the mess I was talking about.

**Comment by gabek** [comment]
Oh and btw the app version is now in `/config`, and I pushed up an update to `app.js` to use it.
