### ISSUE TITLE
Use minio sdk?

### ISSUE THREAD

**Issue by graywolf336** [gabek/owncast#4]
Have you thought about using the minio sdk instead of the aws one?

https://github.com/minio/minio-go

**Comment by gabek** [comment]
I haven't!  What are the benefits?  Thanks for the suggestion!

**Comment by graywolf336** [comment]
Quite honest, not 100% sure what the benefits are over the two. I tried to look into it, but failed to find any valid reason to choose one over the other.

Appreciate the work you guys are doing!

**Comment by gabek** [comment]
It looks like it's scoped just to object storage, and not the entire AWS service set.  That might make it much more lightweight than importing the entire AWS SDK like it is now.  That in itself is worth investigating.  Thanks for the kind words and bringing up this alternative!

**Comment by graywolf336** [comment]
Ah, yeah that is true and you're right, a very great improvement if it makes the binary smaller. :)
