### ISSUE TITLE
Chat toggle disappears

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#43]
Somehow the chat toggle button disappeared on my iPad.

![image](https://user-images.githubusercontent.com/414923/86878425-b2c6e880-c09d-11ea-8094-029c9ae1855c.png)

**Comment by gingervitis** [comment]
Oh interesting, did you just rotate your iPad and then it disappeared?

**Comment by gabek** [comment]
It happened when I went into side-by-side mode on the iPad and the browser resized.  It might be completely specific to that scenario.  I should try it with Safari instead of Brave.

**Comment by gingervitis** [comment]
Ok makes sense. So I had some code in there that hides the chat upon a window resize/rotation on tablets, out of concern that the avail chat window space would be not be useful at certain sizes as well as prioritized the real estate the video. 

I could take that out if it's too confusing an experience.

**Comment by gabek** [comment]
Ginger made changes.  Closing.
