### ISSUE TITLE
Web server started hanging during live stream

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#44]
Tonight while live streaming something happened that I *think* made the web server start hanging.  I'm guessing it was the web server, anyway.

@gingervitis said that calls to things like `/config` and `stream.m3u8` were hanging, so that's why it seems like the web server was hanging issues.  It wasn't serving video, so that has nothing to do with it.

![image](https://user-images.githubusercontent.com/414923/86878724-67f9a080-c09e-11ea-8ea5-44d651d228ed.png)

One thing of note, at one point during the stream the viewer count went up to > 50, so I'm assuming that's connected.  Somebody was watching with VLC and originally didn't know the URL, so I'm wondering if he tried to guess the URL, and then VLC somehow made the web server go nuts, creating a bunch of invalid "viewers", and causing some kind of issue from there.  This is all a guess.

![image](https://user-images.githubusercontent.com/414923/86878521-eace2b80-c09d-11ea-86b5-caeb74718d80.png)

> Update, it eventually started working on desktop browser -- took like five minutes to sync up

**Comment by gabek** [comment]
Another thing that might be to blame, was maybe there was a reconnect loop for the websocket somewhere?  https://github.com/gabek/owncast/blob/master/webroot/js/app.js#L83

Though 50 connections is nothing so that seems unlikely to be the core problem.

**Comment by gingervitis** [comment]
I've been in the process of refactoring a lot of the JS setup and finding a lot of room for clean up and consolidation. Pretty sure I can find some optimizations around the reconnect logic.

**Comment by gabek** [comment]
I haven't seen this happen again so I'm going to close.
