### ISSUE TITLE
Display viewer count while offline?

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#66]
Questions for anybody who has thoughts.  Mostly @gingervitis 

* Should we show viewer counts while offline?
* Should we only show *some* counts while offline?  (Like not current viewers, but maybe max viewers?)
* If we should show current viewers, do we count viewers even while offline?  Does 1 person visiting an offline page show as 1 viewer or 0 viewers?

My opinion?  I think for now we should be simple and just hide viewer counts when offline.

**Comment by graywolf336** [comment]
Maybe have the same cool down which applies to hide the chat?
