### ISSUE TITLE
Building is failing due to resource limitations

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#71]
https://github.com/gabek/owncast/issues/52#issuecomment-660662164

**Comment by gabek** [comment]
@mattdsteele On the same machine(s) you're building on now, did the builds used to work?  Do you remember what build you had that did work?  My first guess was that the sqlite + cgo addition pushed it over the edge, but then I remembered you already were building with cgo, so that's not it.

**Comment by gabek** [comment]
```
go build -toolexec '/usr/bin/time'
# github.com/gabek/owncast/core/chat
        0.08 real         0.07 user         0.04 sys
# github.com/gabek/owncast/core
        0.04 real         0.07 user         0.01 sys
# github.com/gabek/owncast/core/rtmp
        0.02 real         0.03 user         0.01 sys
# github.com/gabek/owncast/controllers
        0.03 real         0.05 user         0.01 sys
# github.com/gabek/owncast/router
        0.01 real         0.02 user         0.00 sys
# github.com/gabek/owncast
        0.01 real         0.02 user         0.00 sys
# github.com/gabek/owncast
        8.33 real         7.49 user         1.20 sys
```

**Comment by gabek** [comment]
@mattdsteele Do you think you could run `go build -toolexec '/usr/bin/time -v' 2> build.txt` on that box and post the resulting file?  It might at least be able to help us track down where it's dying.

**Comment by mattdsteele** [comment]
I first checked out and successfully built at 965c213d5916c5c5db333328a29a863a82c64570. which it looks like was just before cgo was added to `build.sh`?

Attaching [build.txt](https://github.com/gabek/owncast/files/4944805/build.txt)

**Comment by gabek** [comment]
I don't know if packages are being built in parallel or not, but maybe try experimenting with `-p n`?

```
	-p n
		the number of programs, such as build commands or
		test binaries, that can be run in parallel.
		The default is the number of CPUs available.

```

**Comment by mattdsteele** [comment]
I tried a few values from `1` to `8` but all got the same `signal killed` response.

For posterity I tried creating a fresh $5 droplet (1GB RAM, Ubuntu 20.04 LTS) and got the same error there. If you're interested in poking around yourself DM me and I can send you the credentials.

**Comment by gabek** [comment]
Makes sense that cgo would be to blame, but I'm a bit stumped what to do next since it's the building that's unhappy.  I'm finding other people experiencing the same thing but usually they just say "oh I increased the memory allocated to that vm and now it's fine".  But that's not something you can do on a provisioned machine.  And removing the features to reduce the requirement of cgo isn't really an answer.  @graywolf336 have you ever experienced this?

I don't expect people to be building this themselves once we start putting out actual releases, but it's unfortunate that you can't if you wanted to.

In the mean time, there's a build script in the project that uses [xgo](https://github.com/karalabe/xgo) for cross compiling if you want to build your own release for linux on another machine.  I've been using this to make linux releases from my mac.  But you have to get xgo working, and that's it's own list of things to deal with.

`./scripts/build.sh 0.0.0-some-version-designator`

It's super slow since (ironically) it's performing a build within a Docker machine.

**Comment by gabek** [comment]
I caved and removed IPFS support from Owncast (#74), and with that the builds are a ton faster to make and end up way smaller.  So *mayyybee* that's enough to push it over the edge and help with this issue.  Faster and smaller means more efficient, so hopefully that amounts in some wins.  Give it a shot?  And I'll cross my fingers :)

**Comment by graywolf336** [comment]
I have not experienced that, but I also haven't tried to build it after the requirement for cgo was added. 🤔

**Comment by mattdsteele** [comment]
@gabek I pulled the latest changes, and can successfully build on the 1GB box, both natively and containerized.

Bummer about losing IPFS, but I think this is the right tradeoff. Thanks!

**Comment by gabek** [comment]
This is fantastic news, thanks for trying and reporting back!  I still wish we could remove cgo as a dependency from the project, but sadly it's a requirement for the sqlite driver.

Let me know if there's anything else that comes up, or if there's anything else that can be beneficial for your stream next month.

**Comment by graywolf336** [comment]
Wonder if we could use another persistent storage option, such as boltdb, with a layer on top of it (such as https://github.com/timshannon/bolthold) or some other embeddable storage option that doesn't require cgo.

**Comment by gabek** [comment]
Bolt is great, but with persisting the chat I wanted a way to query it for recent items by timestamp, filter out `visible = false` items, etc.  It's much faster to do that within the database than to pull all the records out and then perform the filtering.  If there was a relational'ish database solution that doesn't require all the overhead I'd be totally up for it, but it seems like the only options fall under nosql territory and key/value pair storage.  I just couldn't find anything that fit the needs that wasn't sqlite.

**Comment by gabek** [comment]
This is what it's being used for now: https://github.com/gabek/owncast/blob/master/core/chat/persistence.go#L71
