### ISSUE TITLE
Next round of testing!

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#79]
Now that the web updates are in I wanted to get some more testing done by people broadcasting through Owncast.  Mostly as a way to see how different variables of software and hardware configurations + network conditions, and bitrate configurations work together.  It seems like each time we fire it up and actually use it something new is learned both from the broadcasting and viewing side.

Also since @mattdsteele's wedding is next month (August 8th?) I'd be nice to feel solid about things before then.

Here's some streaming I hope to schedule:

- @controlfreakstudio Are you still up for trying out Owncast for a live stream?  I'm happy to have you use my server if you'd like, or you can run your own. 
- I'll get @gingervitis to do some Animal Crossing commentary streaming 🐱.
- My friend Rebecca wants to do a live stream of a book reading.
- I'll be doing another DJ set stream in the next week or so.

If anybody knows of anybody who's looking to stream online and wants a place to do it, I'm always happy to host them on my test server goth.land.

**Comment by mattdsteele** [comment]
Yup, August 8 is my deadline; I'll send a link to y'all when it's ready to go :)

I'll do some more testing, but the main things I need are to have the RTMP ingress and HLS streams be solid, and thus far I've experienced zero issues so far, so I'm feeling good!

**Comment by controlfreakstudio** [comment]
both. i can simulcast to yours on Sunday 0200 UTC. also will setup my own server this week.

**Comment by gingervitis** [comment]
Ok I'll claim an Animal Crossing test stream this Thursday night sometime maybe around 9pm PT.

**Comment by gabek** [comment]
Just had a game streaming friend give streaming to goth.land a shot.  It worked really well, looked great, no buffering.  He was sending at 2500k, and my owncast config spit out 2000k and 1000k streams.

![Uploading image.png…]()

**Comment by gabek** [comment]
@controlfreakstudio Super exciting!  Let me know if you run into any issues getting the server up and running.

**Comment by gabek** [comment]
Going to chat with @jhannah tomorrow and see if he wants to give it a spin from the broadcasting side.

**Comment by jhannah** [comment]
Can I / do I use SLOBS / OBS? Or I install Owncast instead? Whatever's helpful to you. (Can Owncast client stream to Twitch?)

**Comment by gabek** [comment]
There's no specific Owncast client but you can absolutely point OBS to my Owncast instance.  It's pretty straightforward just by changing what RTMP server you point to.  https://github.com/gabek/owncast#usage-with-obs

You're also totally welcome to pull down Owncast and run an instance yourself if you're interested in doing so!  We haven't yet cut an official "download and run" release, but that's what I'm working towards.  But I could send you an ad-hoc release if you were interested.  You can also build from source or go the Docker route: https://github.com/gabek/owncast/blob/master/doc/quickstart.md

Thanks for offering to help test!

**Comment by jhannah** [comment]
@gabek so... you need to tell me the "Stream Key" you put in your `config.yaml` of `goth.land` (for "user" `dferret`)?

**Comment by gabek** [comment]
Yup exactly!  No users, just the stream key for authentication.

**Comment by jhannah** [comment]
@gabek so ... are you going to tell me what the "Stream Key" is? Presumably it'd take me 2 billion years to guess it randomly. :)

**Comment by gabek** [comment]
Last night @gingervitis did some game streaming and it went well.  Not a single instance of buffering or video issues.

Near the end I noticed some audio/video sync issues, but I honestly think that was the capture device because I've never seen this occur before, and I found posts of other people experiencing it on the same device.  I'm bringing it up in case anybody else notices it when viewing an Owncast stream.  You never know.

Here's the video config I've been using with have been working well on my $10/mo Linode machine.  It usually sits around 50-60% cpu with these two.

```
    - high:
      videoBitrate: 2000
      encoderPreset: veryfast

    - medium:
      videoBitrate: 1200
      encoderPreset: superfast
```

**Comment by gabek** [comment]
Further testing is scheduled:

* Game Time with DeactivatedUser Saturday July 25, 12 noon Pacific.
* DJ Set with controlfreak Saturday July 25, 7pm Pacific.
* DJ Set with gabek Tuesday July 28, 7pm Pacific.
* Rebecca Readz with Rebecca Thursday July 30, 6pm Pacific.

**Comment by gabek** [comment]
Note to myself: Spend some time with mobile RTMP apps and find some apps/settings to recommend to people.

**Comment by gabek** [comment]
Tonight at 8pm Pacific is the last of our scheduled test streams.

Rebecca Stavick will be doing Adult Story Time and reading to whoever tunes into goth.land.  She'll be broadcasting live using her phone and [Larix Broadcaster](https://apps.apple.com/us/app/larix-broadcaster/id1042474385).

**Comment by gabek** [comment]
btw as an aside, with regards to Larix Broadcaster for iOS, they have this neat tool where you can encode all of your broadcasting settings into a URL and/or QR code and you the broadcasting app will automatically configure itself with those settings.  Pretty cool if you want somebody to be able to broadcast easily.

https://softvelum.com/larix/grove/

**Comment by gabek** [comment]
Rebecca's streaming just using her phone + Larix worked great.  Done with mass scheduled testing for now, I'm happy with how it's all gone!
