### ISSUE TITLE
owncast crashes after incoming stream

### ISSUE THREAD

**Issue by graywolf336** [gabek/owncast#8]
```
$ go run *.go
INFO[0000] Owncast v0.0.0/localdev (unknown)            
INFO[0000] Resetting file directories to a clean slate. 
----- Stream offline!  Showing offline state!
Enabling passthrough video
/usr/local/bin/ffmpeg -hide_banner -i doc/logo.png -i webroot/thumbnail.png -filter_complex "[0:v]scale=2640:2360[bg];[bg][1:v]overlay=200:250:enable='between(t,0,3)'"  -f hls -hls_time 4 -hls_playlist_type event -master_pl_name stream.m3u8 -strftime 1 -use_localtime 1 -hls_flags temp_file -tune zerolatency -g 50  -keyint_min 50 -framerate 25 -preset superfast -sc_threshold 0 -profile:v main -pix_fmt yuv420p -var_stream_map "v:0" -hls_segment_filename webroot/hls/%v/offline-%s.ts webroot/hls/%v/stream.m3u8
<nil>
INFO[0000] RTMP server is listening for incoming stream on port 1935. 
INFO[0000] Starting public web server on port 8181      
Enabling passthrough video
PANI[0041] exit status 1                                
panic: (*logrus.Entry) (0x52af2a0,0xc000250070)

goroutine 101 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00013a000, 0xc0005c8570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000250000, 0xc000000000, 0xc000082ee0, 0x1, 0x1)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc00013a000, 0xc000000000, 0xc000082ee0, 0x1, 0x1)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
main.verifyError(...)
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/utils.go:38
main.fireThumbnailGenerator(0xc00020cff0, 0xb)
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/thumbnailGenerator.go:71 +0x4dd
main.startThumbnailGenerator.func1(0xc000218910, 0xc00020cff0, 0xb, 0xc00027e6c0)
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/thumbnailGenerator.go:21 +0x4f
created by main.startThumbnailGenerator
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/thumbnailGenerator.go:17 +0x97
exit status 2
```

Here is my streaming preferences from ProPresenter 7.1.1:
<img width="385" alt="Screen Shot 2020-06-18 at 5 24 19 PM" src="https://user-images.githubusercontent.com/850391/85077720-90216e00-b188-11ea-998b-0d13da049ed2.png">

However, when streaming from OBS at 1920x1080 60fps it doesn't crash.

**Comment by gabek** [comment]
Interesting!  That's a good find.

If you want to uncomment https://github.com/gabek/owncast/blob/master/thumbnailGenerator.go#L68 you can see the actual ffmpeg invocation.  It should be using the most recent segment generated and build a static image out of it.  If you want to send along that invocation and that `.ts` file that it's trying to use I can reproduce it on my side and find what it's unhappy about.

Also, as an experiment, could you try turning off `passthrough` in the config file?  I'm curious if re-encoding the incoming stream would fix it.

**Comment by graywolf336** [comment]
[stream-20200618-1592522663.ts.zip](https://github.com/gabek/owncast/files/4801684/stream-20200618-1592522663.ts.zip)

`ffmpeg -y -i webroot/hls/0/stream-20200618-1592522663.ts -ss 00:00:01.000 -vframes 1 webroot/thumbnail.png`

Curiously, I noticed that I was getting a ton of dropped frames when running locally. And generally when the dropped frames went up this happened.

I turned off the `passthrough` and it happened a lot less but still occurred every so often.

**Comment by graywolf336** [comment]
Does the server need to panic when the thumbnail generation fails? Or can that fail silently or without panic?

**Comment by gabek** [comment]
Not at all, I've defaulted to panics simply so it would draw attention to things that fail so they can be fixed.

**Comment by gabek** [comment]
Awesome, thank you for sending that along, it helped me figure out what's going on with creating a thumbnail from that specific segment.  It tries to pull a thumbnail 1 second into a segment, and this particular segment is less than a second long.  Changing it to pull from 00:00:00 fixes it:

`ffmpeg -i stream-20200618-1592522663.ts -ss 00:00:00.000 -vframes 1 test.png`

It would actually make the most sense to find a way to pull the last frame out of the segment instead of a specific timestamp.  The last frame would be most relevant for a thumbnail, anyway.  And then regardless if a segment is a minute long or less than a second long it won't care.  I'm going to look into that.

Thanks again!

**Comment by gabek** [comment]
As for thumbnail generation causing additional issues with dropped frames, I guess it could make sense, since it's doing more work at that particular point in time.  Since thumbnail generation is low-priority maybe there's a way we can tell it to not work so hard.  I'll look into that too.

**Comment by graywolf336** [comment]
Makes sense to me.

I keep getting it now that I've moved to a DO $5 machine. And what's really interesting is that whenever I start streaming, it will be good for a while but then it suddenly starts dropping a ton of frames. Here's a screen recording of it:

[Screen Recording 2020-06-18 at 7.17.25 PM.zip](https://github.com/gabek/owncast/files/4801787/Screen.Recording.2020-06-18.at.7.17.25.PM.zip)

**Comment by gabek** [comment]
I just pushed a couple thumbnail related changes:

* Use JPG instead of PNG since it seems it's a little faster.
* Limit ffmpeg to using 1 thread.
* Pull the first frame out of the segment instead of a hardcoded location to fix the original crash.  I'd still like to pull the *last* frame, but that requires seeking, and would take longer.

```
ffmpeg -hide_banner -threads 1 -y -t 1 -i stream-20200618-1592522663.ts -f     0.09s user 0.02s system 97% cpu 0.110 total

ffmpeg -hide_banner -y -t 1 -i stream-20200618-1592522663.ts -f image2  1   0.18s user 0.05s system 161% cpu 0.140 total
```

It takes longer, but takes less CPU to do so.

Hopefully these changes make some difference.  I agree that turning it off completely for people is a valid option, as well as a customizable time (it's hardcoded for every 20 seconds now),  but I'd like to see if these changes help.  

Let me know if these help!

**Comment by graywolf336** [comment]
So far locally, it is working amazing! 👏 

However, my DO droplet isn't doing so hot. Both OBS and ProPresenter show they are working fine for about six seconds but then they drop down to under 100 bits per second. So, I don't know if it is the droplet, my internet, or owncast :/ I have poor upload speed, so I'm going to try again tomorrow when I'm somewhere that has ample upload speed.

Will close this issue as it is fixed, so far, and the above paragraph is about something else (seemingly).

**Comment by gabek** [comment]
Awesome, every little bit helps.  Thanks so much for helping with this.  I look forward to continue to squeeze more performance out of things so it can work well on a $5 machine.  I'm running it under a Linode $5 machine and while it runs, it certainly pegs things.  Let me know if there's any other performance increases you can think of when trying it out in your particular environments.
