### ISSUE TITLE
Stream Status Flashes Every Couple of Seconds

### ISSUE THREAD

**Issue by graywolf336** [gabek/owncast#88]
The stream status (timer, viewer count, etc) flashes every couple of seconds
![Screen Recording 2020-07-25 at 4 37 37 PM](https://user-images.githubusercontent.com/850391/88466791-9dbbc900-ce95-11ea-97e9-aabf68808a06.gif)

**Comment by gabek** [comment]
Was just talking about that with @gingervitis this weekend!  It's pretty annoying for sure.  I'm guessing it's a pretty easy fix.
